### ISSUE TITLE
Disconnected environments

### ISSUE THREAD

**Issue by dlewis7444** [hybrid-cloud-patterns/patterns-operator#29]
How doable is using this operator in a disconnected environment?

We're having issues with imageContentSourcePolicies right now but I suspect it's a problem on our mirror (this is a new set up).  But I'm thinking we're going to have further issues too - with connecting to github, for example.  We haven't yet given the clusters access to an organization git repo.

**Comment by mbaldessari** [comment]
Hi @dlewis7444 ,

on paper, I would think that the operator should work on disconnected environments. I.e. as long as the git repo and any other needed artifact is accessible in the disconnected environment, this should just work.
We have not tested it just yet (it's on our shopping list though), so if there are any issues, we'd be happy to look into them

**Comment by mbaldessari** [comment]
I am going to close this one for now, do let me know if it does not work in your environment. Thanks!
